kind = "mobile"
previewPath = "/mobile"
title = "Jump the Book (Mobile)"
version = "1.0.0"
id = "artifacts/jump-the-book"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile" ]
localPort = 21128

[services.development]
run = "pnpm --filter @workspace/jump-the-book run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/jump-the-book", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/jump-the-book", "run", "serve" ]

[services.env]
PORT = "21128"
BASE_PATH = "/mobile"
