import {
  pgTable,
  text,
  integer,
  timestamp,
  jsonb,
  uuid,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { appUsersTable, userBooksTable } from "./userLibrary";

/**
 * A reusable "book bible" for a user-added book.
 *
 * Generated by the smart setup wizard from public web context (publisher
 * blurbs, fan/series wikis, GPT training knowledge of popular books) and
 * confirmed/edited by the user. Used to ground spoiler-safe scene generation
 * for books we have no full text of (Kindle, Audible, modern bestsellers).
 *
 * One bible per user_book (uniqueIndex on userBookId).
 */
export const bookBiblesTable = pgTable(
  "book_bibles",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userBookId: uuid("user_book_id")
      .notNull()
      .references(() => userBooksTable.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => appUsersTable.userId, { onDelete: "cascade" }),
    contextVersion: integer("context_version").notNull().default(1),
    // Identity / shelf
    series: text("series"),
    bookNumber: integer("book_number"),
    genre: jsonb("genre").notNull().default([]), // string[]
    tone: jsonb("tone").notNull().default([]), // string[]
    // World
    settingSummary: text("setting_summary"),
    visualStyleHints: jsonb("visual_style_hints").notNull().default([]), // string[]
    nonSpoilerSummary: text("non_spoiler_summary"),
    publisherBlurb: text("publisher_blurb"),
    // Lists — each {name, description?}
    factions: jsonb("factions").notNull().default([]),
    locations: jsonb("locations").notNull().default([]),
    species: jsonb("species").notNull().default([]),
    ships: jsonb("ships").notNull().default([]),
    technology: jsonb("technology").notNull().default([]),
    importantObjects: jsonb("important_objects").notNull().default([]),
    // Characters: {name, role, description, visualTraits[], aliases[]}
    characterProfiles: jsonb("character_profiles").notNull().default([]),
    // Sources: {title, url, type}
    sources: jsonb("sources").notNull().default([]),
    // User
    userNotes: text("user_notes").notNull().default(""),
    focusAreas: jsonb("focus_areas").notNull().default([]), // string[]
    avoidNotes: text("avoid_notes").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    userBookUniq: uniqueIndex("book_bibles_user_book_uniq").on(t.userBookId),
  }),
);

export type BookBibleRow = typeof bookBiblesTable.$inferSelect;
export type BookBibleInsert = typeof bookBiblesTable.$inferInsert;
